### ISSUE TITLE
Sources in package.yaml

### ISSUE THREAD

**Issue by afoeder** [julianlam/Scrollable#10]
In order to get the packager to work, the package.yaml should provide information about the sources used. I'll provide a pull request.

**Comment by julianlam** [comment]
Hi afoeder - unfortunately, wishbase/Scrollable seems to be a dead link...

**Comment by afoeder** [comment]
Hi Julian, could you retry it please?

**Comment by julianlam** [comment]
Thanks for noticing the omission, afoeder!

**Comment by afoeder** [comment]
gladly; it's just because the Packager doesn't work well otherwise :)
