### ISSUE TITLE
MooTools Forge Dependencies

### ISSUE THREAD

**Issue by dArignac** [julianlam/Scrollable#20]
Howdy,

the MooTools Forge page is missing the dependency Element.Shortcuts. Took some time debugging to find it ;)

Cheers,
Alex

**Comment by julianlam** [comment]
That's true, I believe I use `.show();` and `.hide();` instead of just `.setStyle('display', 'none');`.

I can remove the dependency, although if you'd like to take a crack at it, that'd be great too

**Comment by dArignac** [comment]
As the dependency has to be given when updating the package in MooTools Forge I cannot do that, it's up to you!

**Comment by julianlam** [comment]
Hi dArignac,

Indeed, that is the case! However, I do think reliance on Element.Shortcuts could be removed altogether, instead of my modifying `package.yml` to reflect its use.

Sadly, we are crunching, and I haven't the time to do this, but in the meantime, I will re-open this issue.

**Comment by dArignac** [comment]
Hey Julian,

I wanted to fix it, but I found what the real problem is. Would it be hide() or show() everything would be fine.
But the error occurs when you scroll, in this case you use the shortcut isVisible(). As this is not simply replacable by a single command, you should probably keep it. If you don't want it, I can move the code into scrollable, but regarding updates etc. MooTools.More would be the better place.

**Comment by julianlam** [comment]
Curses...

Looks like I'll have to add the dependency line after all. Thanks for your hard work, dArignac!

**Comment by julianlam** [comment]
Resolved in latest revision of code.
